// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHt8CtCpNB2NFX59tq-ZNkYoIzKfDMec8',
    appId: '1:339672413407:android:75dba567af3f1b6c36e56a',
    messagingSenderId: '339672413407',
    projectId: 'ride-with-purpose',
    storageBucket: 'ride-with-purpose.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyX916fmuOLz5a6ZP78omaNylkNv67Gh4',
    appId: '1:339672413407:ios:d90be4dc22a9f05536e56a',
    messagingSenderId: '339672413407',
    projectId: 'ride-with-purpose',
    storageBucket: 'ride-with-purpose.firebasestorage.app',
    androidClientId: '339672413407-6vuuh10i3f2to5gsi84cevu66ml0kjts.apps.googleusercontent.com',
    iosClientId: '339672413407-8mb421e0sfnig8qmep79g7u0nn1nno6i.apps.googleusercontent.com',
    iosBundleId: 'com.appscrub.rwpcustomer',
  );

}